# kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: football-scout-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: football-scout-api
  template:
    metadata:
      labels:
        app: football-scout-api
    spec:
      containers:
      - name: api
        image: football-scout-api:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: REDIS_URL
          value: redis://redis-service:6379
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
---
apiVersion: batch/v1
kind: Job
metadata:
  name: video-processor
spec:
  template:
    spec:
      containers:
      - name: processor
        image: football-scout-processor:latest
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: 1  # GPU for video processing
      restartPolicy: OnFailure